<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsOrg\Mapping\OrganizationableInterface'     => __DIR__ . '/src/Mapping/OrganizationableInterface.php',
    'CmsOrg\Mapping\OrganizationInterface'         => __DIR__ . '/src/Mapping/OrganizationInterface.php',
    'CmsOrg\Mapping\PositionableInterface'         => __DIR__ . '/src/Mapping/PositionableInterface.php',
    'CmsOrg\Mapping\PositionInterface'             => __DIR__ . '/src/Mapping/PositionInterface.php',
    'CmsOrg\Mapping\Traits\OrganizationableTrait'  => __DIR__ . '/src/Mapping/Traits/OrganizationableTrait.php',
    'CmsOrg\Mapping\Traits\PositionableTrait'      => __DIR__ . '/src/Mapping/Traits/PositionableTrait.php',
    'CmsOrg\Module'                                => __DIR__ . '/src/Module.php',
    'CmsOrg\Mvc\Controller\AdminController'        => __DIR__ . '/src/Mvc/Controller/AdminController.php',
    'CmsOrg\Mvc\Controller\OrganizationController' => __DIR__ . '/src/Mvc/Controller/OrganizationController.php',
    'CmsOrgTest\Framework\TestCase'                => __DIR__ . '/tests/CmsOrg/Framework/TestCase.php',
    'CmsOrgTest\SampleTest'                        => __DIR__ . '/tests/CmsOrg/SampleTest.php',
);
